# This is a basic workflow to help you get started with Actions

name: vscode nodejs cache

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: '.github/workflows/vscode.yml'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: overlay 
    
    - name: Checkout vscode
      uses: actions/checkout@v2
      with:
        repository: microsoft/vscode
        ref: 'release/1.45'
        path: vscode

    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Apply patch for vscode
      run: |
        cd $GITHUB_WORKSPACE/vscode
        git apply $GITHUB_WORKSPACE/overlay/app-editors/vscode/files/*

    - name: Download and crate yarn cache
      run: |
        cd $GITHUB_WORKSPACE/vscode
        echo 'yarn-offline-mirror "offline-cache"' >> .yarnrc
        yarn --frozen-lockfile --ignore-scripts
        yarn postinstall --frozen-lockfile
        tar cJf ../vscode-yarn-offline-cache.tar.xz offline-cache
        
    - name: Download builtin extensions
      run: |
        cd $GITHUB_WORKSPACE/vscode
        yarn download-builtin-extensions
        cd .build
        tar cJf ../../vscode-builtin-extensions.tar.xz builtInExtensions
      
    - uses: actions/upload-artifact@v2
      with:
        name: vscode-yarn-offline-cache
        path: $GITHUB_WORKSPACE/vscode-yarn-offline-cache.tar.xz

    - uses: actions/upload-artifact@v2
      with:
        name: vscode-yarn-offline-cache
        path: $GITHUB_WORKSPACE/vscode-builtin-extensions.tar.xz
