name: Create vscode nodejs cache (Release)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: overlay 
    
    - name: Checkout vscode
      uses: actions/checkout@v2
      with:
        repository: microsoft/vscode
        ref: '1.51.1'
        path: vscode

    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Download yarn cache
      working-directory: ${{ github.workspace }}/vscode
      run: |
        yarn --frozen-lockfile --ignore-scripts
        yarn postinstall --frozen-lockfile

    - name: Download builtin extensions
      working-directory: ${{ github.workspace }}/vscode
      run: |
        yarn download-builtin-extensions
        cd .build
        tar cJf ../../vscode-builtin-extensions.tar.xz builtInExtensions

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Nodejs cache for vscode 1.51.1
        prerelease: true

    - name: Upload builtin extensions
      id: upload-release-asset_2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/vscode-builtin-extensions.tar.xz
        asset_name: vscode-builtin-extensions.tar.xz
        asset_content_type: application/x-xz
